### ISSUE TITLE
Error fetching catalogs

### ISSUE THREAD

**Issue by lukavdplas** [UUDigitalHumanitieslab/EDPOP#186]
Currently, if I start up a local server from the `develop` branch, catalogues won't load. Console shows the following message:

> Uncaught Response has no @graph key, is this JSON-LD in compacted form?

@tijmenbaarda I see you wrote the `JsonLdCollection` that throws this exception; any idea what's going wrong here?

**Comment by tijmenbaarda** [comment]
I don't get this error on the latest develop branch. Could you show the contents of the response?

**Comment by tijmenbaarda** [comment]
Ah, I see, the context is missing. That is likely because a version of `restframework-rdf` is installed that does not have the JSON-LD context support yet. The version of `restframework-rdf` in requirements should be pointing at the git version, but I will make a release later today, because pointing at git branches in requirements.txt does not always work well.
