### ISSUE TITLE
VRE front end showing blank page

### ISSUE THREAD

**Issue by linguistcrg** [UUDigitalHumanitieslab/EDPOP#198]
The VRE front end page is blank. On my browser's terminal, I see the following error:
```
ReferenceError: util is not defined
    at main.js:139:11
```

**Comment by tijmenbaarda** [comment]
Thanks for spotting this! It seems that this problem only occurs when using docker-compose (I normally don't use that and I didn't have this problem, but when I start docker the problem occurs.

The last line of `bundle.js` is:
```
})(_, jQuery, Backbone, _.backbone-util, _, _.isFunction, _.isNumber, _.isString, _.isObject, _.isArray, _.escape);
```

I will investigate...

**Comment by jgonggrijp** [comment]
@tijmenbaarda it probably has something to do with the `globals` parameter in the Rollup config.

**Comment by tijmenbaarda** [comment]
Ah, yes, it was somewhere there. I think Rollup thought `backbone-util` was a global because it was not installed.

@linguistcrg : you can probably solve the problem by running `npm install` (through Docker: `docker-compose exec frontend npm install`, and then making sure that the JavaScript bundle is recreated, for example by restarting the docker containers.

You may also have to install the new Python dependencies, using `docker-compose exec backend pip install -r requirements.txt`.

I hope this solves the problem!

**Comment by linguistcrg** [comment]
It worked, thanks!
