### ISSUE TITLE
Always show the same set of fields per record type

### ISSUE THREAD

**Issue by tijmenbaarda** [UUDigitalHumanitieslab/EDPOP#229]

**Comment by jgonggrijp** [comment]
I think you mean when displaying a record in the frontend?

**Comment by tijmenbaarda** [comment]
Yes! Both in the table view and the list view a fixed set of fields should be shown. This should probably be the fields as defined in the record ontology. Currently the table view shows all fields that are present in one or more records, and the detail view only shows the fields that are present in that particular record.

In the table view some fields may be hidden by default, but they should always be defined.

This is per Jeroen's request, because he wants to be able to annotate fields that are not filled in.

**Comment by jgonggrijp** [comment]
@tijmenbaarda in https://github.com/UUDigitalHumanitieslab/EDPOP/pull/233#pullrequestreview-2464458280:

> What I meant with #229 (and maybe I had not formulated it clearly) was also to show _only_ the fields that belong to the specific record type (like extent, which would only show on `BibliographicalRecord`). However, I think that the code in this PR prepares well for this with the functions in `tabulator-utils.js`.

Do you mean you also want to exclude the only-biographical fields from the hidden-but-available columns in the tabulator view of an only-bibliographical catalog (and vice versa)? Because in that case we need a way to distinguish between only-biographical, only-bibliographical and mixed catalogs. Likewise for collections.

Writing this out, I realize this probably isn't worth the effort. We can still do it for the record detail view, of course.
